Copy to s3 on hbase and aws s3 during install

diff --git a/deploy/packaging/docker/build-rpm/deploy-geowave-to-hdfs.sh.template b/deploy/packaging/docker/build-rpm/deploy-geowave-to-hdfs.sh.template
--- a/deploy/packaging/docker/build-rpm/deploy-geowave-to-hdfs.sh.template
+++ b/deploy/packaging/docker/build-rpm/deploy-geowave-to-hdfs.sh.template
@@ -17,6 +17,11 @@ dependency_tests() {
     done
 }
 
+read_dom () {
+    local IFS=\>
+    read -d \< ENTITY CONTENT
+}
+
 # Sanity check of environment
 dependency_tests
 
@@ -127,7 +132,7 @@ fi
 # Upload library to hdfs
 su $HDFS_USER -c "hadoop fs -put $GEOWAVE_DATASTORE_HOME/geowave-$DATASTORE_TOKEN-$VENDOR_VERSION.jar $DATASTORE_LIB_DIR/geowave-$DATASTORE_TOKEN-$VENDOR_VERSION.jar"
 if [ $? -ne 0 ]; then
-echo >&2 "Unable to upload geowave-$DATASTORE_TOKEN-$VENDOR_VERSION.jar into hdfs. Aborting."; exit 1;
+    echo >&2 "Unable to upload geowave-$DATASTORE_TOKEN-$VENDOR_VERSION.jar into hdfs. Aborting."; exit 1;
 fi
 
 # Also upload the build metadata file for ease of inspection
@@ -147,6 +152,25 @@ if [ $? -ne 0 ]; then
     echo >&2 "Unable to change ownership of the $DATASTORE_LIB_DIR directory in hdfs. Aborting."; exit 1;
 fi
 
-echo "EXPORT VARS"
-export -p
+GOTELEM=0
+# If using Hbase on AWS, scan hbase configs, find configured bucket and copy library over.
+if [[ -x "$(command -v aws)" ]] && [ -f /etc/hbase/conf/hbase-site.xml ]; then
+  while read_dom; do
+    if [[ -z  "$(echo -e "${CONTENT}" | tr -d '[:space:]')"  ]]; then
+      continue;
+    fi
 
+    if [[ $ENTITY = "name" ]] && [ $CONTENT = "hbase.rootdir" ]; then
+      GOTELEM=1;
+      continue
+    fi
+
+    if [[ $GOTELEM -eq 1 ]] && [[ $CONTENT = "s3://"* ]]; then
+      aws cp $GEOWAVE_DATASTORE_HOME/geowave-$DATASTORE_TOKEN-$VENDOR_VERSION.jar $CONTENT/lib/geowave-tools-$VENDOR_VERSION-apache.jar
+    fi
+
+    if [ $GOTELEM -eq 1 ]; then
+      break
+    fi
+  done < /etc/hbase/conf/hbase-site.xml
+fi
